name: mochigami-manager

services:
  manager:
    build: ./manager
    container_name: mochigami-manager
    restart: always
    network_mode: "host"
    extra_hosts:
      - "YOSSYHUB-PC.local:192.168.11.120"
    environment:
      - TZ=Asia/Tokyo
      - PYTHONUNBUFFERED=1
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SSH_PASSWORD=${SSH_PASSWORD}
    volumes:
      - ./manager:/app
      - /data/compose/discord-bot:/data/compose/discord-bot
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  watchdog:
    build: ./manager
    container_name: mochigami-watchdog
    restart: always
    network_mode: "host"
    extra_hosts:
      - "YOSSYHUB-PC.local:192.168.11.120"
    environment:
      - TZ=Asia/Tokyo
      - PYTHONUNBUFFERED=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    command: ["python", "watchdog.py"]
